'use client';

import { Dispatch, FormEvent, SetStateAction, useMemo, useState } from 'react';

export type AccountingEntry = {
  id:string; date:string; createdAt:string; type:'RECEIPT'|'PAYMENT'|'TRANSFER';
  sourceFund:string; destinationFund:string; amount:number; subject:string; person:string;
  reference:string; branch:string; status:'ثبت‌شده'|'در انتظار تسویه'|'تسویه‌شده';
  fee:number; cost:number; channel:string; parentId?:string;
};
export type ExpenseRecord = {
  id:string; code:string; date:string; expenseType:'جاری'|'سرمایه‌ای'; category:string;
  subject:string; amount:number; paidAmount:number; supplier:string; fund:string;
  paymentType:string; spender:string; description:string; branch:string;
};
export type AccountingPerson = {id:string;name:string;mobile:string;kind:'حقیقی'|'حقوقی';role:string;description:string};
export type ExpenseCategory = {id:string;name:string;description:string};

type Props = {
  active:string; entries:AccountingEntry[]; setEntries:Dispatch<SetStateAction<AccountingEntry[]>>;
  expenses:ExpenseRecord[]; setExpenses:Dispatch<SetStateAction<ExpenseRecord[]>>;
  people:AccountingPerson[]; setPeople:Dispatch<SetStateAction<AccountingPerson[]>>;
  categories:ExpenseCategory[]; setCategories:Dispatch<SetStateAction<ExpenseCategory[]>>;
  funds:string[]; notify:(message:string)=>void;
};

const money=(value:number)=>Math.round(value).toLocaleString('fa-IR')+' تومان';
const qty=(value:number)=>value.toLocaleString('fa-IR');
const isoDate=()=>new Date().toISOString().slice(0,10);
const uid=(prefix:string)=>prefix+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
const formatDate=(date:string)=>date?new Date(date+'T12:00:00').toLocaleDateString('fa-IR'):'—';
const monthKey=(date:string)=>date?new Intl.DateTimeFormat('fa-IR-u-ca-persian-nu-latn',{year:'numeric',month:'2-digit'}).format(new Date(date+'T12:00:00')).replace('/','-'):'بدون تاریخ';
const monthLabel=(key:string)=>{if(key==='بدون تاریخ')return key;const [year,month]=key.split('-').map(Number);const names=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];return (year.toLocaleString('fa-IR',{useGrouping:false})+' '+(names[month-1]||month))};
const isCardFund=(name:string)=>/کارت|درگاه|پوز|pos/i.test(name);

export function fundBalance(entries:AccountingEntry[],fund:string){
  return entries.reduce((total,entry)=>total+(entry.destinationFund===fund?entry.amount:0)-(entry.sourceFund===fund?entry.amount:0),0);
}

function Modal({title,onClose,children,footer}:{title:string;onClose:()=>void;children:React.ReactNode;footer:React.ReactNode}){
  return <div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="modal-card" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="close-btn" onClick={onClose}>⊗ بستن</button></header><div className="modal-body">{children}</div><footer>{footer}</footer></section></div>;
}

function Stats({items}:{items:Array<[string,string,string?]>}){
  return <div className="flow-stats">{items.map(([label,value,hint])=><article key={label}><span>{label}</span><b>{value}</b>{hint&&<small>{hint}</small>}</article>)}</div>;
}

function Empty({text='هنوز سندی ثبت نشده است.'}:{text?:string}){return <div className="empty-state">{text}</div>}

export default function AccountingWorkspace({active,entries,setEntries,expenses,setExpenses,people,setPeople,categories,setCategories,funds,notify}:Props){
  const [modal,setModal]=useState<'receipt'|'payment'|'transfer'|'summary'|'expense'|'category'|'person'|'settle'|'payExpense'|null>(null);
  const [targetId,setTargetId]=useState('');
  const [query,setQuery]=useState('');
  const [fromDate,setFromDate]=useState('');
  const [toDate,setToDate]=useState('');
  const filteredEntries=useMemo(()=>entries.filter(entry=>(!query||Object.values(entry).some(value=>String(value).includes(query)))&&(!fromDate||entry.date>=fromDate)&&(!toDate||entry.date<=toDate)),[entries,query,fromDate,toDate]);
  const receipts=filteredEntries.filter(entry=>entry.type==='RECEIPT').reduce((sum,entry)=>sum+entry.amount,0);
  const payments=filteredEntries.filter(entry=>entry.type==='PAYMENT').reduce((sum,entry)=>sum+entry.amount,0);
  const totalFunds=funds.reduce((sum,fund)=>sum+fundBalance(entries,fund),0);
  const outstanding=expenses.reduce((sum,expense)=>sum+Math.max(0,expense.amount-expense.paidAmount),0);
  const pendingSettlements=entries.filter(entry=>entry.type==='RECEIPT'&&entry.status==='در انتظار تسویه');
  const sales=entries.filter(entry=>entry.type==='RECEIPT'&&entry.channel==='فروش');
  const purchaseEntries=entries.filter(entry=>entry.type==='PAYMENT'&&entry.channel==='خرید مواد اولیه');

  const ensureFund=(fund:string)=>{if(!fund){notify('ابتدا صندوق را در تنظیمات ← صندوق تعریف کنید.');return false}return true};
  const ensureFunds=(source:string,amount:number)=>{if(!ensureFund(source))return false;const balance=fundBalance(entries,source);if(balance<amount){notify('موجودی '+source+' کافی نیست؛ موجودی فعلی '+money(balance)+' است.');return false}return true};
  const ensureReference=(reference:string)=>{if(reference&&entries.some(entry=>entry.reference===reference)){notify('شماره مرجع تکراری است.');return false}return true};

  const submitEntry=(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;
    const amount=Number(data.amount||0);if(amount<=0){notify('مبلغ باید بزرگ‌تر از صفر باشد.');return}
    const type=modal==='receipt'?'RECEIPT':modal==='payment'?'PAYMENT':'TRANSFER';
    const source=type==='RECEIPT'?'':data.sourceFund||data.fund||'';const destination=type==='PAYMENT'?'':data.destinationFund||data.fund||'';
    if((type!=='RECEIPT'&&!ensureFunds(source,amount))||(type!=='PAYMENT'&&!ensureFund(destination))||!ensureReference(data.reference||''))return;
    if(type==='TRANSFER'&&source===destination){notify('صندوق مبدأ و مقصد نمی‌توانند یکسان باشند.');return}
    const entry:AccountingEntry={id:uid('acc'),date:data.date||isoDate(),createdAt:new Date().toISOString(),type,sourceFund:source,destinationFund:destination,amount,subject:data.subject||'سند مالی',person:data.person||'—',reference:data.reference||uid('REF'),branch:'شعبه مرکزی',status:type==='RECEIPT'&&isCardFund(destination)?'در انتظار تسویه':'ثبت‌شده',fee:0,cost:0,channel:'ثبت دستی'};
    setEntries(current=>[entry,...current]);setModal(null);notify(type==='RECEIPT'?'دریافت ثبت و موجودی صندوق افزایش یافت.':type==='PAYMENT'?'پرداخت ثبت و موجودی صندوق کسر شد.':'انتقال بین صندوق‌ها ثبت شد.');
  };

  const submitExpense=(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;const amount=Number(data.amount||0);const paidAmount=Math.min(amount,Math.max(0,Number(data.paidAmount||0)));
    if(amount<=0){notify('مبلغ هزینه باید بزرگ‌تر از صفر باشد.');return}if(!data.category){notify('دسته‌بندی هزینه الزامی است.');return}if(paidAmount>0&&!ensureFunds(data.fund||'',paidAmount))return;
    const code=data.code||'COST-'+String(expenses.length+1).padStart(4,'0');if(expenses.some(item=>item.code===code)){notify('کد هزینه تکراری است.');return}
    const expense:ExpenseRecord={id:uid('cost'),code,date:data.date||isoDate(),expenseType:(data.expenseType==='سرمایه‌ای'?'سرمایه‌ای':'جاری'),category:data.category,subject:data.subject||'هزینه',amount,paidAmount,supplier:data.supplier||'—',fund:data.fund||'—',paymentType:data.paymentType||'بانکی',spender:data.spender||'مدیر شعبه',description:data.description||'',branch:'شعبه مرکزی'};
    setExpenses(current=>[expense,...current]);if(paidAmount>0)setEntries(current=>[{id:uid('acc'),date:expense.date,createdAt:new Date().toISOString(),type:'PAYMENT',sourceFund:expense.fund,destinationFund:'',amount:paidAmount,subject:expense.subject,person:expense.supplier,reference:expense.code,branch:expense.branch,status:'ثبت‌شده',fee:0,cost:0,channel:'هزینه',parentId:expense.id},...current]);setModal(null);notify(paidAmount===amount?'هزینه و پرداخت کامل آن ثبت شد.':'هزینه ثبت شد و مانده بدهی ایجاد شد.');
  };

  const payExpense=(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const expense=expenses.find(item=>item.id===targetId);if(!expense)return;const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;const due=expense.amount-expense.paidAmount;const amount=Number(data.amount||0);if(amount<=0||amount>due){notify('مبلغ پرداخت باید بین صفر و مانده هزینه باشد.');return}if(!ensureFunds(data.fund||'',amount))return;
    setExpenses(current=>current.map(item=>item.id===expense.id?{...item,paidAmount:item.paidAmount+amount,fund:data.fund}:item));setEntries(current=>[{id:uid('acc'),date:data.date||isoDate(),createdAt:new Date().toISOString(),type:'PAYMENT',sourceFund:data.fund,destinationFund:'',amount,subject:'پرداخت مانده '+expense.subject,person:expense.supplier,reference:expense.code+'-'+String(expense.paidAmount+amount),branch:expense.branch,status:'ثبت‌شده',fee:0,cost:0,channel:'هزینه',parentId:expense.id},...current]);setModal(null);notify('پرداخت مانده هزینه ثبت شد.');
  };

  const settle=(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();const source=entries.find(entry=>entry.id===targetId);if(!source)return;const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;const fee=Math.max(0,Number(data.fee||0));const target=data.targetFund||'';if(!ensureFund(target)||target===source.destinationFund||fee>=source.amount){notify('صندوق مقصد یا کارمزد معتبر نیست.');return}if(!ensureFunds(source.destinationFund,source.amount))return;
    const transfer:AccountingEntry={id:uid('settle'),date:data.date||isoDate(),createdAt:new Date().toISOString(),type:'TRANSFER',sourceFund:source.destinationFund,destinationFund:target,amount:source.amount-fee,subject:'تسویه '+source.reference,person:source.person,reference:'SET-'+source.reference,branch:source.branch,status:'تسویه‌شده',fee:0,cost:0,channel:'تسویه',parentId:source.id};
    const feeEntry:AccountingEntry={id:uid('fee'),date:transfer.date,createdAt:new Date().toISOString(),type:'PAYMENT',sourceFund:source.destinationFund,destinationFund:'',amount:fee,subject:'کارمزد تسویه '+source.reference,person:'شرکت پرداخت',reference:'FEE-'+source.reference,branch:source.branch,status:'ثبت‌شده',fee,cost:0,channel:'کارمزد',parentId:source.id};
    setEntries(current=>[...(fee?[feeEntry]:[]),transfer,...current.map(entry=>entry.id===source.id?{...entry,status:'تسویه‌شده' as const,fee}:entry)]);setModal(null);notify('تسویه ثبت و مبلغ خالص به صندوق مقصد منتقل شد.');
  };

  const addCategory=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;if(!data.name.trim()){notify('نام دسته‌بندی الزامی است.');return}if(categories.some(item=>item.name===data.name.trim())){notify('این دسته‌بندی قبلاً ثبت شده است.');return}setCategories(current=>[{id:uid('cat'),name:data.name.trim(),description:data.description||''},...current]);setModal(null);notify('دسته‌بندی هزینه ثبت شد.');};
  const addPerson=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;if(!data.name.trim()||!data.mobile.trim()){notify('نام و شماره همراه الزامی است.');return}if(people.some(item=>item.mobile===data.mobile.trim())){notify('این شماره همراه قبلاً ثبت شده است.');return}setPeople(current=>[{id:uid('person'),name:data.name.trim(),mobile:data.mobile.trim(),kind:data.kind==='حقوقی'?'حقوقی':'حقیقی',role:data.role||'مشتری',description:data.description||''},...current]);setModal(null);notify('شخص جدید ثبت شد.');};

  const pageTitle:Record<string,string>={finance:'گزارش مالی',settlement:'گزارش تسویه','financial-analysis':'گزارش تحلیل مالی','branch-analysis':'گزارش تحلیل شعبه‌ها',ledger:'گزارش گردش حساب','expense-categories':'دسته‌بندی هزینه‌ها',expenses:'هزینه‌ها',people:'اشخاص'};
  const monthRows=[...new Set([...entries.map(entry=>monthKey(entry.date)),...expenses.map(expense=>monthKey(expense.date))])].filter(Boolean).sort().reverse();
  const title=pageTitle[active]||'حسابداری';
  return <>
    <div className="page-head"><div><p className="eyebrow">دفتر یکپارچه مالی · اطلاعات واقعی ثبت‌شده</p><h1>{title} <span className="info-icon">ⓘ</span></h1></div><div className="head-actions">{active==='finance'&&<><button className="primary" onClick={()=>setModal('receipt')}>＋ ثبت دریافت</button><button className="ghost" onClick={()=>setModal('payment')}>＋ ثبت پرداخت</button><button className="ghost" onClick={()=>setModal('transfer')}>انتقال بین صندوق‌ها</button><button className="mint-btn" onClick={()=>setModal('summary')}>جمع‌بندی</button></>}{active==='expenses'&&<button className="primary" onClick={()=>setModal('expense')}>＋ ایجاد هزینه</button>}{active==='expense-categories'&&<button className="primary" onClick={()=>setModal('category')}>＋ دسته‌بندی جدید</button>}{active==='people'&&<button className="primary" onClick={()=>setModal('person')}>＋ مشتری جدید</button>}<button className="excel-btn" onClick={()=>notify('خروجی این گزارش از داده‌های ثبت‌شده آماده است.')}>X خروجی اکسل</button></div></div>
    {['finance','settlement','financial-analysis','branch-analysis','ledger','expenses'].includes(active)&&<Stats items={active==='settlement'?[['در انتظار تسویه',money(pendingSettlements.reduce((sum,item)=>sum+item.amount,0))],['تعداد تراکنش',qty(pendingSettlements.length)],['کارمزد ثبت‌شده',money(entries.filter(item=>item.channel==='کارمزد').reduce((sum,item)=>sum+item.amount,0))],['تسویه‌شده',money(entries.filter(item=>item.channel==='تسویه').reduce((sum,item)=>sum+item.amount,0))]]:[['جمع دریافت',money(receipts)],['جمع پرداخت',money(payments)],['مانده کل صندوق‌ها',money(totalFunds)],['تعهد پرداخت‌نشده',money(outstanding)]]}/>} 
    {['finance','ledger'].includes(active)&&<div className="bill-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="جستجو در اسناد"/><input aria-label="از تاریخ" type="date" value={fromDate} onChange={event=>setFromDate(event.target.value)}/><input aria-label="تا تاریخ" type="date" value={toDate} onChange={event=>setToDate(event.target.value)}/></div>}
    <section className="panel data-panel"><div className="table-scroll">
      {active==='finance'?<table><thead><tr><th>تاریخ پرداخت</th><th>تاریخ ثبت</th><th>برداشت از</th><th>انتقال به</th><th>مبلغ</th><th>بابت</th><th>نوع</th><th>مرجع</th><th>نام شخص</th><th>وضعیت</th></tr></thead><tbody>{filteredEntries.map(entry=><tr key={entry.id}><td>{formatDate(entry.date)}</td><td>{new Date(entry.createdAt).toLocaleString('fa-IR')}</td><td>{entry.sourceFund||'—'}</td><td>{entry.destinationFund||'—'}</td><td>{money(entry.amount)}</td><td>{entry.subject}</td><td>{entry.type==='RECEIPT'?'دریافت':entry.type==='PAYMENT'?'پرداخت':'انتقال'}</td><td>{entry.reference}</td><td>{entry.person}</td><td><span className={'badge '+(entry.status==='در انتظار تسویه'?'inactive':'')}>{entry.status}</span></td></tr>)}</tbody></table>:
      active==='settlement'?<table><thead><tr><th>عملیات</th><th>مبلغ تراکنش</th><th>کارمزد</th><th>شماره پیگیری</th><th>تاریخ</th><th>صندوق پذیرنده</th><th>مبلغ در انتظار</th><th>مبلغ تسویه‌شده</th><th>وضعیت</th></tr></thead><tbody>{entries.filter(entry=>entry.type==='RECEIPT'&&isCardFund(entry.destinationFund)).map(entry=><tr key={entry.id}><td>{entry.status==='در انتظار تسویه'?<button className="ghost" onClick={()=>{setTargetId(entry.id);setModal('settle')}}>ثبت تسویه</button>:'—'}</td><td>{money(entry.amount)}</td><td>{money(entry.fee)}</td><td>{entry.reference}</td><td>{formatDate(entry.date)}</td><td>{entry.destinationFund}</td><td>{money(entry.status==='در انتظار تسویه'?entry.amount:0)}</td><td>{money(entry.status==='تسویه‌شده'?entry.amount-entry.fee:0)}</td><td><span className={'badge '+(entry.status==='در انتظار تسویه'?'inactive':'')}>{entry.status}</span></td></tr>)}</tbody></table>:
      active==='financial-analysis'?<table><thead><tr><th>ماه</th><th>فروش</th><th>خرید مواد اولیه</th><th>بهای مصرف رسپی</th><th>هزینه‌های جاری</th><th>اجاره</th><th>هزینه سرمایه‌ای</th><th>سود عملیاتی</th><th>درصد هزینه</th></tr></thead><tbody>{monthRows.map(month=>{const monthSales=sales.filter(item=>monthKey(item.date)===month).reduce((sum,item)=>sum+item.amount,0);const material=purchaseEntries.filter(item=>monthKey(item.date)===month).reduce((sum,item)=>sum+item.amount,0);const cogs=sales.filter(item=>monthKey(item.date)===month).reduce((sum,item)=>sum+item.cost,0);const current=expenses.filter(item=>monthKey(item.date)===month&&item.expenseType==='جاری'&&item.category!=='خرید مواد اولیه'&&!item.category.includes('اجاره')).reduce((sum,item)=>sum+item.amount,0);const rent=expenses.filter(item=>monthKey(item.date)===month&&item.category.includes('اجاره')).reduce((sum,item)=>sum+item.amount,0);const capital=expenses.filter(item=>monthKey(item.date)===month&&item.expenseType==='سرمایه‌ای').reduce((sum,item)=>sum+item.amount,0);const profit=monthSales-cogs-current-rent-capital;const ratio=monthSales?Math.round((cogs+current+rent+capital)/monthSales*100):0;return <tr key={month}><td>{monthLabel(month)}</td><td>{money(monthSales)}</td><td>{money(material)}</td><td>{money(cogs)}</td><td>{money(current)}</td><td>{money(rent)}</td><td>{money(capital)}</td><td className={profit<0?'negative':'positive'}>{money(profit)}</td><td>{qty(ratio)}٪</td></tr>})}</tbody></table>:
      active==='branch-analysis'?<table><thead><tr><th>شعبه</th><th>فروش</th><th>هزینه عملیاتی</th><th>بهای مصرف</th><th>سود</th><th>تعداد فاکتور</th><th>میانگین فاکتور</th><th>مانده صندوق‌ها</th></tr></thead><tbody>{['شعبه مرکزی'].map(branch=>{const branchSales=sales.filter(item=>item.branch===branch).reduce((sum,item)=>sum+item.amount,0);const branchCost=sales.filter(item=>item.branch===branch).reduce((sum,item)=>sum+item.cost,0);const branchExpense=expenses.filter(item=>item.branch===branch&&item.category!=='خرید مواد اولیه').reduce((sum,item)=>sum+item.amount,0);return <tr key={branch}><td>{branch}</td><td>{money(branchSales)}</td><td>{money(branchExpense)}</td><td>{money(branchCost)}</td><td className={branchSales-branchExpense-branchCost<0?'negative':'positive'}>{money(branchSales-branchExpense-branchCost)}</td><td>{qty(sales.filter(item=>item.branch===branch).length)}</td><td>{money(sales.filter(item=>item.branch===branch).length?branchSales/sales.filter(item=>item.branch===branch).length:0)}</td><td>{money(totalFunds)}</td></tr>})}</tbody></table>:
      active==='ledger'?<table><thead><tr><th>شخص</th><th>بدهکار</th><th>بستانکار</th><th>صندوق</th><th>بابت</th><th>مرجع</th><th>تاریخ</th></tr></thead><tbody>{filteredEntries.filter(entry=>entry.person&&entry.person!=='—').map(entry=><tr key={entry.id}><td>{entry.person}</td><td>{entry.type==='PAYMENT'?money(entry.amount):'۰'}</td><td>{entry.type==='RECEIPT'?money(entry.amount):'۰'}</td><td>{entry.sourceFund||entry.destinationFund}</td><td>{entry.subject}</td><td>{entry.reference}</td><td>{formatDate(entry.date)}</td></tr>)}</tbody></table>:
      active==='expense-categories'?<table><thead><tr><th>عملیات</th><th>نام دسته‌بندی</th><th>توضیحات</th><th>تعداد هزینه</th><th>مجموع</th></tr></thead><tbody>{categories.map(category=><tr key={category.id}><td><button className="danger-text" disabled={expenses.some(item=>item.category===category.name)} onClick={()=>setCategories(current=>current.filter(item=>item.id!==category.id))}>حذف</button></td><td>{category.name}</td><td>{category.description||'—'}</td><td>{qty(expenses.filter(item=>item.category===category.name).length)}</td><td>{money(expenses.filter(item=>item.category===category.name).reduce((sum,item)=>sum+item.amount,0))}</td></tr>)}</tbody></table>:
      active==='expenses'?<table><thead><tr><th>عملیات</th><th>کد هزینه</th><th>نوع پرداخت</th><th>تاریخ</th><th>صندوق</th><th>دسته‌بندی</th><th>هزینه‌کننده</th><th>تأمین‌کننده</th><th>مانده</th><th>مبلغ</th><th>نوع هزینه</th><th>بابت</th></tr></thead><tbody>{expenses.map(expense=><tr key={expense.id}><td>{expense.amount>expense.paidAmount?<button className="ghost" onClick={()=>{setTargetId(expense.id);setModal('payExpense')}}>پرداخت مانده</button>:'تسویه کامل'}</td><td>{expense.code}</td><td>{expense.paymentType}</td><td>{formatDate(expense.date)}</td><td>{expense.fund}</td><td>{expense.category}</td><td>{expense.spender}</td><td>{expense.supplier}</td><td>{money(expense.amount-expense.paidAmount)}</td><td>{money(expense.amount)}</td><td>{expense.expenseType}</td><td>{expense.subject}</td></tr>)}</tbody></table>:
      <table><thead><tr><th>نام و نام خانوادگی</th><th>شماره همراه</th><th>نوع</th><th>نقش</th><th>بدهکار</th><th>بستانکار</th><th>مانده</th><th>توضیحات</th></tr></thead><tbody>{people.map(person=>{const personEntries=entries.filter(entry=>entry.person===person.name);const debit=personEntries.filter(entry=>entry.type==='PAYMENT').reduce((sum,item)=>sum+item.amount,0);const credit=personEntries.filter(entry=>entry.type==='RECEIPT').reduce((sum,item)=>sum+item.amount,0);return <tr key={person.id}><td>{person.name}</td><td>{person.mobile}</td><td>{person.kind}</td><td>{person.role}</td><td>{money(debit)}</td><td>{money(credit)}</td><td>{money(credit-debit)}</td><td>{person.description||'—'}</td></tr>})}</tbody></table>}
    </div>{((active==='finance'&&!filteredEntries.length)||(active==='settlement'&&!entries.some(entry=>entry.type==='RECEIPT'&&isCardFund(entry.destinationFund)))||(active==='financial-analysis'&&!monthRows.length)||(active==='expenses'&&!expenses.length)||(active==='expense-categories'&&!categories.length)||(active==='people'&&!people.length)||(active==='ledger'&&!filteredEntries.length))&&<Empty/>}</section>
    {(modal==='receipt'||modal==='payment'||modal==='transfer')&&<Modal title={modal==='receipt'?'ثبت دریافت':modal==='payment'?'ثبت پرداخت':'انتقال بین صندوق‌ها'} onClose={()=>setModal(null)} footer={<button className="primary" form="entry-form" type="submit">ثبت قطعی</button>}><form id="entry-form" className="form-grid" onSubmit={submitEntry}><div className="form-field"><label>تاریخ*</label><input name="date" type="date" defaultValue={isoDate()} required/></div>{modal!=='receipt'&&<div className="form-field"><label>برداشت از صندوق*</label><select name={modal==='transfer'?'sourceFund':'fund'} defaultValue="" required><option value="" disabled>انتخاب کنید</option>{funds.map(fund=><option key={fund}>{fund}</option>)}</select></div>}{modal!=='payment'&&<div className="form-field"><label>انتقال به صندوق*</label><select name={modal==='transfer'?'destinationFund':'fund'} defaultValue="" required><option value="" disabled>انتخاب کنید</option>{funds.map(fund=><option key={fund}>{fund}</option>)}</select></div>}<div className="form-field"><label>نام شخص</label><input name="person" list="people-list"/><datalist id="people-list">{people.map(person=><option key={person.id} value={person.name}/>)}</datalist></div><div className="form-field"><label>مبلغ (تومان)*</label><input name="amount" type="number" min="1" required/></div><div className="form-field"><label>شماره مرجع</label><input name="reference"/></div><div className="form-field wide"><label>بابت*</label><textarea name="subject" required/></div></form></Modal>}
    {modal==='expense'&&<Modal title="ثبت هزینه جدید" onClose={()=>setModal(null)} footer={<button className="primary" form="expense-form" type="submit">ثبت هزینه</button>}><form id="expense-form" className="form-grid" onSubmit={submitExpense}><div className="form-field"><label>کد هزینه</label><input name="code" placeholder="خودکار"/></div><div className="form-field"><label>نوع هزینه*</label><select name="expenseType"><option>جاری</option><option>سرمایه‌ای</option></select></div><div className="form-field"><label>دسته‌بندی*</label><select name="category" defaultValue="" required><option value="" disabled>انتخاب کنید</option>{categories.map(category=><option key={category.id}>{category.name}</option>)}</select></div><div className="form-field"><label>بابت*</label><input name="subject" required/></div><div className="form-field"><label>تاریخ*</label><input name="date" type="date" defaultValue={isoDate()} required/></div><div className="form-field"><label>مبلغ هزینه*</label><input name="amount" type="number" min="1" required/></div><div className="form-field"><label>مبلغ پرداخت‌شده</label><input name="paidAmount" type="number" min="0" defaultValue="0"/></div><div className="form-field"><label>برداشت از صندوق</label><select name="fund" defaultValue=""><option value="">بدون پرداخت</option>{funds.map(fund=><option key={fund}>{fund}</option>)}</select></div><div className="form-field"><label>تأمین‌کننده</label><input name="supplier" list="people-list"/></div><div className="form-field"><label>نوع پرداخت</label><select name="paymentType"><option>بانکی</option><option>نقدی</option><option>کارت‌خوان</option></select></div><div className="form-field"><label>فرد هزینه‌کننده</label><input name="spender"/></div><div className="form-field wide"><label>توضیحات</label><textarea name="description"/></div></form></Modal>}
    {modal==='category'&&<Modal title="دسته‌بندی جدید" onClose={()=>setModal(null)} footer={<button className="primary" form="category-form" type="submit">ثبت</button>}><form id="category-form" className="form-grid" onSubmit={addCategory}><div className="form-field"><label>نام دسته‌بندی*</label><input name="name" required/></div><div className="form-field wide"><label>توضیحات</label><textarea name="description"/></div></form></Modal>}
    {modal==='person'&&<Modal title="ثبت مشتری جدید" onClose={()=>setModal(null)} footer={<button className="primary" form="person-form" type="submit">ثبت شخص</button>}><form id="person-form" className="form-grid" onSubmit={addPerson}><div className="form-field"><label>نوع شخص*</label><select name="kind"><option>حقیقی</option><option>حقوقی</option></select></div><div className="form-field"><label>نام و نام خانوادگی/شرکت*</label><input name="name" required/></div><div className="form-field"><label>شماره همراه*</label><input name="mobile" required/></div><div className="form-field"><label>نقش</label><select name="role"><option>مشتری</option><option>تأمین‌کننده</option><option>کارمند</option><option>سهام‌دار</option></select></div><div className="form-field wide"><label>توضیحات</label><textarea name="description"/></div></form></Modal>}
    {modal==='payExpense'&&<Modal title="پرداخت مانده هزینه" onClose={()=>setModal(null)} footer={<button className="primary" form="pay-expense-form" type="submit">ثبت پرداخت</button>}><form id="pay-expense-form" className="form-grid" onSubmit={payExpense}><div className="form-field"><label>تاریخ*</label><input name="date" type="date" defaultValue={isoDate()} required/></div><div className="form-field"><label>برداشت از صندوق*</label><select name="fund" defaultValue="" required><option value="" disabled>انتخاب کنید</option>{funds.map(fund=><option key={fund}>{fund}</option>)}</select></div><div className="form-field"><label>مبلغ پرداخت*</label><input name="amount" type="number" min="1" max={expenses.find(item=>item.id===targetId)?.amount||0} required/></div></form></Modal>}
    {modal==='settle'&&<Modal title="ثبت تسویه کارت‌خوان/درگاه" onClose={()=>setModal(null)} footer={<button className="primary" form="settle-form" type="submit">ثبت تسویه</button>}><form id="settle-form" className="form-grid" onSubmit={settle}><div className="form-field"><label>تاریخ تسویه*</label><input name="date" type="date" defaultValue={isoDate()} required/></div><div className="form-field"><label>انتقال به صندوق/بانک*</label><select name="targetFund" defaultValue="" required><option value="" disabled>انتخاب کنید</option>{funds.filter(fund=>fund!==entries.find(entry=>entry.id===targetId)?.destinationFund).map(fund=><option key={fund}>{fund}</option>)}</select></div><div className="form-field"><label>کارمزد</label><input name="fee" type="number" min="0" defaultValue="0"/></div></form></Modal>}
    {modal==='summary'&&<Modal title="جمع‌بندی مالی و صندوق" onClose={()=>setModal(null)} footer={<button className="primary" onClick={()=>setModal(null)}>بستن</button>}><Stats items={[['جمع دریافت‌ها',money(receipts)],['جمع پرداخت‌ها',money(payments)],['خالص جریان نقد',money(receipts-payments)],['تعهد پرداخت‌نشده',money(outstanding)]]}/><div className="fund-balance-list">{funds.map(fund=><div key={fund}><span>{fund}</span><b className={fundBalance(entries,fund)<0?'negative':'positive'}>{money(fundBalance(entries,fund))}</b></div>)}</div></Modal>}
  </>;
}
