// Initial database contents, seeded from the current on-page Persian copy.
// Menu categories/items come from server/data/menu-seed.json (Jan Majnoon Lounge).
const menuSeed = require('./data/menu-seed.json');

module.exports = {
  settings: {
    siteTitle: 'Westo — منوی کافه و رستوران',
    metaDescription:
      'منوی آنلاین وستو؛ دسته‌ها، جزئیات غذاها و ثبت سفارش روی تیبل.',
    adminPhones: ['09374333028'],
    otpTtlMs: 2 * 60 * 1000,
  },
  content: {
    'nav.login': 'ورود',
    'nav.menu': 'منو',
    'nav.contact': 'تماس',
    'nav.sound_on': 'روشن',
    'nav.sound_off': 'خاموش',
    'nav.link.gamme': 'دسته‌ها',
    'nav.link.benefits': 'مزایا',
    'nav.link.faq': 'سؤالات متداول',
    'nav.link.newsletter': 'خبرنامه',
    'nav.copyright': '© ۲۰۲۶ Westo',
    'hero.scroll_hint': 'برای دیدن غذاها اسکرول کنید',
    'ingredients.sugar.badge': '۱۱ گرم شکر',
    'ingredients.sugar.title1': 'شکر',
    'ingredients.sugar.title2': 'کمتر',
    'ingredients.sugar.desc':
      'یک نوشیدنی انرژی‌زا با شکر کمتر، فقط با شکر نیشکر؛ انتخاب‌شده به‌خاطر منشأ گیاهی و طعم خوشایندش.',
    'ingredients.aroma.badge': 'طعم‌دهنده‌های مصنوعی',
    'ingredients.aroma.title1': 'طعم‌دهنده‌های',
    'ingredients.aroma.title2': 'طبیعی',
    'ingredients.aroma.desc':
      'برای قدرت عطر و غنای طعم، طعم‌دهنده‌های طبیعی برگرفته از میوه‌ها و گیاهان را با وسواس انتخاب کرده‌ایم.',
    'ingredients.caffeine.badge': 'کافئین مصنوعی',
    'ingredients.caffeine.title': 'کافئین از دانه‌های قهوه',
    'ingredients.caffeine.desc':
      'برای انرژی، دانه‌های قهوه را انتخاب کرده‌ایم؛ منبع طبیعی کافئین، در کنار گوارانا که آن هم طبیعی است.',
    'ingredients.stevia.badge': 'آسپارتام، سوکرالوز، آسه‌سولفام K',
    'ingredients.stevia.title': 'استویا',
    'ingredients.stevia.desc':
      'برای تکمیل شکر نیشکر و افزودن شیرینی و لذت، یک شیرین‌کننده گیاهی با عصاره استویا اضافه کرده‌ایم.',
    'faq.title1': 'سؤالات',
    'faq.title2': 'متداول',
    'newsletter.title': 'به ما بپیوندید',
    'newsletter.desc': 'برای اطلاع از منوی فصل و پیشنهادهای ویژه وستو ایمیل خود را ثبت کنید.',
    'newsletter.email_label': 'آدرس ایمیل شما',
    'newsletter.submit': 'ثبت‌نام',
    'newsletter.consent': 'با ثبت‌نام، شما می‌پذیرید:',
    'newsletter.privacy_link': 'سیاست حریم خصوصی',
    'newsletter.success': 'ثبت‌نام شما تأیید شد.',
    'newsletter.error': 'ثبت‌نام شما تأیید نشد.',
    'footer.copyright': '© ۲۰۲۶ Westo',
    'footer.legal': 'اطلاعات حقوقی',
    'footer.cgu': 'شرایط استفاده',
    'footer.privacy': 'سیاست حریم خصوصی',
    'footer.tiktok': 'تیک‌تاک',
    'footer.instagram': 'اینستاگرام',
    'logo.white': 'assets/images/brand/westo-wordmark.png',
    'logo.black': 'assets/images/brand/westo-wordmark.png',
    'entrance.pattern': 'assets/images/entrance/westo-pattern.webp',
  },
  // Carousel slides = every menu category that has dishes (one slot per
  // category, same order as menuCategories filtered to non-empty).
  products: [
    {
      id: 1,
      name1: 'سالاد',
      name2: '',
      shortDesc: 'سالادهای تازه وستو؛ از مرغ گریل تا کینوا و میگو، با درسینگ‌های خانگی.',
      longDesc: 'دسته سالاد: برگ‌های تازه، پروتئین گریل‌شده و درسینگ‌های مخصوص — سبک، سالم و خوش‌طعم.',
    },
    {
      id: 2,
      name1: 'پیش',
      name2: 'غذا',
      shortDesc: 'پیش‌غذاهای وستو؛ تاکو، وینگز، فرایز و حمص برای شروع میز.',
      longDesc: 'دسته پیش‌غذا: از تاکو میگو و پارمسان وینگز تا حمص بالحم — لقمه‌های کوچک با طعم بزرگ.',
    },
    {
      id: 3,
      name1: 'پاستا',
      name2: '',
      shortDesc: 'پاستاهای وستو؛ ریگاتونی با سس‌های خامه‌ای و مخصوص.',
      longDesc: 'دسته پاستا: چیکن آلفردو، چیکن پارمسان و بیشتر — پخت روز با پنیر پارمزان.',
    },
    {
      id: 4,
      name1: 'برگر',
      name2: '',
      shortDesc: 'برگرهای دست‌ساز وستو با نان بریوش و سیب‌زمینی سرخ‌شده.',
      longDesc: 'دسته برگر: گوشت تازه چرخ‌شده روزانه، نان بریوش و سس‌های خانگی در کنار فرایز.',
    },
    {
      id: 5,
      name1: 'غذای',
      name2: 'اصلی',
      shortDesc: 'غذاهای اصلی وستو؛ استیک، فیله و بشقاب‌های کامل.',
      longDesc: 'دسته غذای اصلی: از تکس مکس و فیله گوساله تا بشقاب‌های مخصوص سرآشپز.',
    },
    {
      id: 6,
      name1: 'پیتزا',
      name2: '',
      shortDesc: 'پیتزاهای ایتالیایی وستو با خمیر ناپولی و پخت تنور.',
      longDesc: 'دسته پیتزا: خمیر ناپولی، پنیر تازه و تاپینگ‌های مخصوص — مستقیم از تنور.',
    },
    {
      id: 7,
      name1: 'سوشی',
      name2: '',
      shortDesc: 'سوشی‌بار وستو؛ رول‌ها و نیگیری‌های تازه روز.',
      longDesc: 'دسته سوشی: از کالیفرنیا کریسپی تا سالمون آووکادو — برنج ژاپنی و ماهی تازه.',
    },
    {
      id: 8,
      name1: 'وگن شو',
      name2: 'وجترین بمان',
      shortDesc: 'انتخاب‌های گیاهی وستو برای وگن‌ها و وجترین‌ها.',
      longDesc: 'دسته وگن و وجترین: بشقاب‌های کاملاً گیاهی با سبزیجات تازه و طعم‌های آسیایی.',
    },
    {
      id: 9,
      name1: 'نات',
      name2: 'کافئین',
      shortDesc: 'نوشیدنی‌های بدون کافئین؛ برای هر ساعت شبانه‌روز.',
      longDesc: 'دسته نات کافئین: نوشیدنی‌های گرم و لطیف بدون کافئین.',
    },
    {
      id: 10,
      name1: 'هربال',
      name2: 'تی',
      shortDesc: 'دمنوش‌های گیاهی وستو؛ آرامش در یک فنجان.',
      longDesc: 'دسته هربال تی: ترکیب‌های گیاهی دم‌آوری‌شده با عطرهای طبیعی.',
    },
    {
      id: 11,
      name1: 'پیستری',
      name2: '',
      shortDesc: 'شیرینی و دسرهای تازه قنادی وستو.',
      longDesc: 'دسته پیستری: کیک‌ها و دسرهای روز — از موس شکلات تا کرم بروله.',
    },
    {
      id: 12,
      name1: 'سرویس',
      name2: 'ویژه',
      shortDesc: 'سرویس‌های ویژه وستو برای مناسبت‌ها و پذیرایی خاص.',
      longDesc: 'دسته سرویس ویژه: چای و پذیرایی مخصوص میز شما.',
    },
  ],
  faq: [
    {
      id: 1,
      q: 'چطور از منوی وستو سفارش بدهم؟',
      a: 'روی هر غذا «افزودن» را بزنید، تعداد را انتخاب کنید و از دکمه تیبل سفارش را ثبت کنید.',
    },
    {
      id: 2,
      q: 'آیا می‌توانم بدون ورود سفارش دهم؟',
      a: 'برای ثبت سفارش فقط شماره میز و موبایل کافی است؛ ورود اختیاری است و برای ذخیره پروفایل به کار می‌آید.',
    },
    {
      id: 3,
      q: 'روش‌های پرداخت چیست؟',
      a: 'می‌توانید در صندوق تسویه کنید یا پرداخت آنلاین را هنگام ثبت سفارش انتخاب کنید.',
    },
    {
      id: 4,
      q: 'آیا منو گیاهی/وگن دارد؟',
      a: 'بله. دسته «وگن شو وجترین بمان» و چند غذای دیگر با برچسب گیاهی در منو موجود است.',
    },
    {
      id: 5,
      q: 'چطور گارسون را صدا بزنم؟',
      a: 'از تیبل، در مرحله پرداخت دکمه «فراخوان گارسون» را بزنید و شماره میز را وارد کنید.',
    },
    {
      id: 6,
      q: 'قیمت‌ها به‌روز هستند؟',
      a: 'قیمت‌ها از پنل مدیریت وستو به‌روزرسانی می‌شوند و همان مبلغ در منو و فاکتور نمایش داده می‌شود.',
    },
  ],
  // Full menu (categories + orderable items), mirrored from Jan Majnoon Lounge.
  menuCategories: menuSeed.categories,
  menuItems: menuSeed.items,
  // Sale-only complements are deliberately separate from menuItems: they can
  // be sold by the POS without appearing on the public guest menu.
  menuComplements: [
    { id: 1, name: 'کوکی شکلاتی', price: 180000, img: 'assets/menu/westo-cookie-complement-v1.webp', available: true, stock: null, lowStockAt: 5 },
    { id: 2, name: 'باقلوا تک‌نفره', price: 190000, img: 'assets/menu/71753.webp', available: true, stock: null, lowStockAt: 5 },
    { id: 3, name: 'سودا کلاسیک', price: 190000, img: 'assets/menu/55791.webp', available: true, stock: null, lowStockAt: 5 },
    { id: 4, name: 'نوشیدنی مالت', price: 280000, img: 'assets/menu/44156.webp', available: true, stock: null, lowStockAt: 5 },
    { id: 5, name: 'لیمون سودا', price: 190000, img: 'assets/menu/104313.webp', available: true, stock: null, lowStockAt: 5 },
  ],
  menuComplementRules: [
    {
      id: 1,
      name: 'همراه نوشیدنی گرم',
      prompt: 'کنار نوشیدنی چه چیزی میل دارید؟',
      sourceCategoryIds: [7675, 7701, 14477, 7676],
      sourceItemIds: [],
      complementIds: [1, 2],
      active: true,
    },
    {
      id: 2,
      name: 'نوشیدنی کنار غذا',
      prompt: 'برای کنار غذا نوشیدنی اضافه شود؟',
      sourceCategoryIds: [7560, 7561, 17007, 7562, 7563, 7564, 7566, 13581, 7567],
      sourceItemIds: [],
      complementIds: [3, 4, 5],
      active: true,
    },
  ],
  // Legacy sample items kept for reference (no longer used).
  legacyMenuItems: [
    {
      id: 1,
      categoryId: 3,
      name: 'نیگیری سالمون',
      desc: 'برش تازه سالمون روی برنج ژاپنی؛ با واسابی و زنجبیل ترشی.',
      price: 185000,
      available: true,
    },
    {
      id: 2,
      categoryId: 3,
      name: 'نیگیری تن',
      desc: 'تن قرمز درجه یک روی برش برنج؛ طعم عمیق و اومامی.',
      price: 195000,
      available: true,
    },
    {
      id: 3,
      categoryId: 3,
      name: 'نیگیری ماهی سفید',
      desc: 'ماهی سفید لطیف با تزئین سبزی؛ سبک و تازه.',
      price: 165000,
      available: true,
    },
    {
      id: 4,
      categoryId: 3,
      name: 'نیگیری آنگی',
      desc: 'مارماهی کبابی با سس تره‌یاکی و کنجد؛ شیرین و دودی.',
      price: 210000,
      available: true,
    },
    {
      id: 5,
      categoryId: 3,
      name: 'ماکی خیار',
      desc: 'رول خیار ترد با نوری و برنج؛ انتخاب گیاهی سبک.',
      price: 95000,
      available: true,
    },
    {
      id: 6,
      categoryId: 3,
      name: 'مجموعه ماکی',
      desc: 'سه رول ماکی (سالمون، تن، خیار) در یک بشقاب؛ برای اشتراک.',
      price: 280000,
      available: true,
    },
  ],
  orders: [],
  paymentAttempts: [],
  checkoutIdempotency: {},
  auditLog: [],
  commandCenter: { schemaVersion: 1, eventRevision: 0 },
  users: [],
  newsletter: [],
  loginLog: [],
  /* Cafe/restaurant ops — Top Menu Market-class gaps */
  restaurant: {
    name: 'وستو',
    brandName: 'Westo',
    tagline: 'کافه و رستوران',
    about: 'وستو فضایی برای غذا، نوشیدنی و دورهمی است؛ منوی زنده، سفارش از میز و مدیریت لحظه‌ای قیمت و موجودی.',
    address: 'مشهد، سجادشهر، نبش تقاطع سجاد و حامد',
    phone: '09159800052',
    whatsapp: '',
    mapUrl: 'https://maps.app.goo.gl/Sb2NpN5nsJ4x5jwE9',
    instagram: '',
    website: 'http://localhost:4180',
    currency: 'تومان',
    taxPercent: 0,
    servicePercent: 0,
  },
  hours: {
    sat: { open: '10:00', close: '23:30', closed: false },
    sun: { open: '10:00', close: '23:30', closed: false },
    mon: { open: '10:00', close: '23:30', closed: false },
    tue: { open: '10:00', close: '23:30', closed: false },
    wed: { open: '10:00', close: '23:30', closed: false },
    thu: { open: '10:00', close: '00:30', closed: false },
    fri: { open: '10:00', close: '00:30', closed: false },
  },
  branches: [
    {
      id: 1,
      slug: 'main',
      name: 'شعبه اصلی',
      address: 'مشهد، سجادشهر، نبش تقاطع سجاد و حامد',
      phone: '09159800052',
      whatsapp: '',
      mapUrl: 'https://maps.app.goo.gl/Sb2NpN5nsJ4x5jwE9',
      active: true,
      hours: {
        sat: { open: '10:00', close: '23:30', closed: false },
        sun: { open: '10:00', close: '23:30', closed: false },
        mon: { open: '10:00', close: '23:30', closed: false },
        tue: { open: '10:00', close: '23:30', closed: false },
        wed: { open: '10:00', close: '23:30', closed: false },
        thu: { open: '10:00', close: '00:30', closed: false },
        fri: { open: '10:00', close: '00:30', closed: false },
      },
    },
  ],
  deliveryZones: [
    {
      id: 1,
      branchId: 1,
      name: 'سجاد و محدوده نزدیک',
      active: true,
      minOrder: 250000,
      fee: 30000,
      etaMinutes: 25,
      sort: 1,
    },
    {
      id: 2,
      branchId: 1,
      name: 'محدوده مرکزی مشهد',
      active: true,
      minOrder: 350000,
      fee: 55000,
      etaMinutes: 40,
      sort: 2,
    },
  ],
  paymentProvider: {
    mode: 'sandbox',
    provider: 'sandbox',
    enabled: true,
  },
  printing: {
    version: 5,
    defaultPrinterId: 'cashier-main',
    printers: [{
      id: 'cashier-main',
      name: 'پرینتر صندوق',
      model: 'bixolon-srp-350iii',
      branchId: 1,
      protocol: 'raw',
      transport: 'network',
      systemPrinterName: '',
      host: '192.168.254.4',
      port: 9100,
      enabled: true,
      paperWidth: 80,
      charsPerLine: 48,
      renderMode: 'raster',
      encoding: 'windows-1256',
      codePage: 40,
      cut: true,
      timeoutMs: 5000,
    }],
  },
  tables: Array.from({ length: 12 }, (_, i) => ({
    id: i + 1,
    label: `میز ${i + 1}`,
    seats: i < 4 ? 2 : i < 8 ? 4 : 6,
    active: true,
    zone: i < 4 ? 'سالن' : i < 8 ? 'تراس' : 'VIP',
    branchId: 1,
  })),
  promotions: [],
  visits: [],
  visitSessions: {},
  waiterCalls: [],
  loyalty: {
    enabled: true,
    pointsPerToman: 0.01,
    redeemValue: 1000,
    welcomePoints: 50,
  },
  loyaltyLedger: [],
  theme: {
    accent: '#78d0d8',
    accentInk: '#0a1a1c',
    surface: '#111318',
    bg: '#08090b',
    fog: '#ece8e2',
    printPaper: '#f7f3ec',
    printInk: '#1a1714',
    printAccent: '#2a7a86',
    radius: 14,
    fontDisplay: 'Vazirmatn',
  },
  reservationSettings: {
    enabled: true,
    slotMinutes: 30,
    maxParty: 12,
    maxCoversPerSlot: 24,
    advanceDays: 21,
    minHoursAhead: 1,
  },
  reservations: [],
};
