'use strict';
const fs=require('fs'); const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const css=read('css/westo-production-v12.css');
const critical=read('css/westo-critical.smart.css');
const index=read('index.html');
const checks=[]; const check=(name,ok)=>checks.push([name,!!ok]);
check('light entrance pattern field rule',css.includes('Light Entrance Material + WESTO Pattern Field'));
check('approved WESTO source artwork used',css.includes("url('../assets/images/entrance/westo-pattern-source.png')"));
check('light café photo suppressed',/data-theme='light'[\s\S]{0,900}eg-ambient__photo[\s\S]{0,140}opacity:\s*0\s*!important/.test(css));
check('light base no black fallback',css.includes("linear-gradient(145deg, #edf1ec 0%, #e8eee8 58%, #e2e9e4 100%)"));
check('main light card translucent',css.includes('rgba(248,250,247,.58) !important'));
check('main card blur restored',css.includes('blur(30px) saturate(1.34)'));
check('shared control liquid shadow token',css.includes('--westo-light-control-shadow'));
check('top controls use liquid material',css.includes("#westo-entrance #eg-site-menu.westo-menu-trigger"));
check('dock/corner liquid material',css.includes("#westo-entrance .eg-dock")&&css.includes("#westo-entrance .eg-corner"));
check('language active capsule',css.includes('.eg-lang-seg.is-active')&&css.includes('background: rgba(255,255,255,.46)'));
check('inactive language readable',css.includes('color: rgba(23,32,31,.48)'));
check('primary CTA teal liquid',css.includes('linear-gradient(105deg, rgba(22,139,148,.88)'));
check('CTA disabled stays branded',css.includes("#westo-entrance .eg-cta.is-busy")&&css.includes('rgba(35,131,139,.68)'));
check('step icons use glass family',css.includes('blur(14px) saturate(1.20)'));
check('economy no live blur',css.includes("data-perf-tier='economy'] #westo-entrance .eg-card"));
check('mobile pattern budget',css.includes('background-size: 300px auto'));
check('higher contrast mode',css.includes('@media (prefers-contrast: more)'));
check('critical bundle keeps light entrance and excludes entrance promo deck',critical.includes('Light Entrance Material + WESTO Pattern Field')&&!critical.includes('WESTO Entrance Promotional Deck v13.6'));
check('root cache bumped',index.includes('westo-critical.smart.css?v=release13r9')&&index.includes('westo-smart-loader.js?v=release13r9'));
const fail=checks.filter(x=>!x[1]);
for(const [n,p] of checks) console.log(`${p?'PASS':'FAIL'}  ${n}`);
console.log(`\nLight Entrance v13.9: ${checks.length-fail.length}/${checks.length}`);
if(fail.length) process.exit(1);
