'use strict';

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');

const index = read('index.html');
const loader = read('js/westo-smart-loader.js');
const table = read('js/table-cart.js');
const three = read('js/three-scene.js');
const menuCss = read('css/menu-story.css');
const glassCss = read('css/westo-glass.css');
const entranceCss = read('css/entrance-gate.css');
const server = read('server/server.js');
const build = read('scripts/build-smart-bundles.js');

const checks = [];
const check = (name, pass) => checks.push({ name, pass: Boolean(pass) });

check('release13r6 loader wired', /westo-smart-loader\.js\?v=release13r6/.test(index) && /const VERSION = ['"]release13r6['"]/.test(loader));
check('combined critical app preloaded', /preload[^>]+westo-app\.smart\.js\?v=release13r6/.test(index));
check('combined app generated by build', /'js\/westo-app\.smart\.js'/.test(build));
check('server early-hints combined app', /westo-app\.smart\.js\?v=release13r6/.test(server));
check('legacy Three import map removed', !/type=["']importmap["']/.test(index));
check('single canonical Three module URL', /import \* as THREE from ['"]\.\/vendor\/three\/three\.module\.js['"]/.test(three));
check('postFX premium-only and dynamic', /postFxCapable\s*=\s*initialPerfTier === ['"]premium['"]/.test(three) && /await import\(\s*['"]\.\/vendor\/three\/westo-postprocessing\.bundle\.mjs\?v=release13r6['"]/.test(three));
check('direct render fallback exists', /renderer\.render\(scene, camera\)/.test(three));
check('economy native Lenis wheel path', /smoothWheel:\s*initialPerfTier !== ['"]economy['"]/.test(three));
check('economy textures disable mipmaps', /generateMipmaps\s*=\s*initialPerfTier !== ['"]economy['"]/.test(three));
check('distant mobile plates are culled', /Math\.abs\(slot\) > 1\.35/.test(three));

check('image delivery avoids image object URLs', /const needsBlobDelivery = task\.kind === ['"]audio['"]/.test(loader));
check('healthy bound images skip rebinding', /img\.dataset\.westoManaged === ['"]1['"][\s\S]*img\.naturalWidth > 0/.test(loader));
check('network budget considers RTT', /rtt\s*>=\s*220/.test(loader));
check('background menu warming is bounded', /maxDishWarm = tier === ['"]premium['"] \? 24 : 8/.test(loader));
check('economy bulk warm is skipped', /tier === ['"]economy['"][\s\S]*background-fill-complete/.test(loader));

check('dish board DOM cache exists', /let allDishBoardsCache/.test(table));
check('dish geometry cache exists', /dishBoardMetrics/.test(table));
check('dish relayout is RAF-coalesced', /function scheduleDishLayoutRefresh/.test(table));
check('category fly is transform-only', /translate3d\(\$\{tx\.toFixed\(2\)\}px,\$\{ty\.toFixed\(2\)\}px,0\) scale/.test(table));
check('category fly no per-frame gsap.set sizing', !/function setCatFlyOrb[\s\S]{0,1300}gsap\.set\(el, props\)/.test(table));
check('catbar forced reflow restart removed', !/void\s+(bar|chip|icon)\.offsetWidth/.test(table));
check('rail computed-position read removed', !/getComputedStyle\(icon\)\.position/.test(table));
check('cat fly will-change is compositor-only', /\.westo-cat-fly__orb[\s\S]{0,500}will-change:\s*transform, opacity/.test(menuCss));

check('economy glass blur disabled', /data-perf-tier=["']economy["'][\s\S]*backdrop-filter:\s*none/.test(menuCss + glassCss + entranceCss));
check('runtime long-task downgrade guard enabled', /PerformanceObserver[\s\S]*longtask-pressure/.test(index));
check('entrance image intrinsic dimensions corrected', /cafe-bokeh\.webp[^>]+width=["']1280["'][^>]+height=["']853["']/.test(index));
check('brand image intrinsic dimensions reserved', /westo-fa-wordmark-dark\.png[^>]+width=["']768["'][^>]+height=["']224["']/.test(index));

const failed = checks.filter((item) => !item.pass);
console.log(JSON.stringify({ pass: failed.length === 0, passed: checks.length - failed.length, failed: failed.length, checks }, null, 2));
process.exitCode = failed.length ? 1 : 0;
