const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8');
let pass=0,fail=0;function check(n,c){if(c){pass++;console.log('PASS',n)}else{fail++;console.error('FAIL',n)}}
const build=read('scripts/build-smart-bundles.js');
const deck=read('js/menu-promo-deck.js');
const css=read('css/menu-promo-deck.css');
const admin=read('js/admin.js');
const server=read('server/server.js');
const db=JSON.parse(read('server/data/db.json'));
check('menu deck source exists',deck.includes("section.is-gamme")&&deck.includes("['menu','both']"));
check('deck mounted into hero section',deck.includes('heroSection.appendChild(root)'));
check('entrance mount removed from smart bundles',!build.includes("'js/entrance-promo-deck.js'"));
check('legacy promo rail removed from smart bundles',!build.includes("'js/promo-slider.js'"));
check('new menu deck in smart bundles',build.includes("'js/menu-promo-deck.js'")&&build.includes("'css/menu-promo-deck.css'"));
check('entrance promo css not bundled',!build.includes("'css/entrance-promo-deck.css'"));
check('legacy promo rail css not bundled',!build.includes("'css/promo-slider.css'"));
check('deck hidden in dish mode',css.includes("html.is-dish-boards #westo-menu-promo-deck { display:none"));
check('deck visible category mode',css.includes("html:not(.is-dish-boards) #westo-menu-promo-deck"));
check('mobile responsive placement',css.includes('@media (max-width:767px)')&&css.includes('--menu-deck-h'));
check('short landscape guard',css.includes('max-height:650px')&&css.includes('orientation:landscape'));
check('no deck backdrop blur surface',!css.includes('.westo-menu-promo-deck__card {\n  -webkit-backdrop-filter'));
check('share blur disabled',css.includes('.westo-menu-promo-deck__share')&&css.includes('-webkit-backdrop-filter:none'));
check('free throw pointer physics retained',deck.includes("pointermove")&&deck.includes('Math.hypot(dx,dy)')&&deck.includes('throwCard'));
check('snapback retained',deck.includes('snapBack'));
check('circular DOM reorder retained',deck.includes('deck.appendChild(current)'));
check('share isolated from drag',deck.includes("closest('.westo-menu-promo-deck__share')")&&deck.includes('stopPropagation'));
check('resource scheduler integration',deck.includes('scheduler.bindImage')&&deck.includes("group:'menu-promo-deck'"));
check('admin menu-only placement',admin.includes("['menu', 'صفحه منو — بین هدر و دسته منتخب']")&&admin.includes("placement: 'menu'"));
check('admin preview targets menu',admin.includes('پیش‌نمایش صفحه منو'));
check('server defaults new promos to menu',server.includes("placement: 'menu', shareEnabled: true"));
check('sample promos migrated to menu',db.promoSlides.every(s=>s.placement==='menu'));
check('cache generation bumped',read('index.html').includes('release13r8')&&server.includes('release13r8'));
console.log(`\n${pass}/${pass+fail} PASS`);process.exit(fail?1:0);
