'use strict';
const fs=require('fs'); const path=require('path'); const ROOT=path.resolve(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8'); const exists=(p)=>fs.existsSync(path.join(ROOT,p));
let pass=0,fail=0; const failures=[]; const check=(n,ok)=>{if(ok)pass++;else{fail++;failures.push(n)}};
const htmls=fs.readdirSync(ROOT).filter(n=>n.endsWith('.html')).sort();
const fontFiles=['assets/fonts/Vazirmatn-Variable.woff2','assets/fonts/6a17254d942eb32e84bde0f0_Geist-Regular.woff2','assets/fonts/6a0d6cd3df7330778e84acee_Geist-Light.woff2','assets/fonts/6a0b0eef462d20ff07b9cbe9_GeistMono-Regular.woff2','assets/fonts/6a0b3ae273b9c591afba279f_Franklin_Gothic_ATF_Black_Italic.woff2'];
fontFiles.forEach(f=>check(`font present ${f}`,exists(f)&&fs.statSync(path.join(ROOT,f)).size>20000));
const vazir=read('css/vazir-system.css');
check('vazirmatn font-face local',/@font-face[\s\S]*Vazirmatn[\s\S]*\.\.\/assets\/fonts\/Vazirmatn-Variable\.woff2/.test(vazir));
check('global UI font uses Vazirmatn',vazir.includes('--westo-ui-font')&&vazir.includes('Vazirmatn'));
check('root critical bundle contains Vazirmatn',read('css/westo-critical.smart.css').includes('Vazirmatn-Variable.woff2'));
check('no external google font dependency',!htmls.some(f=>/fonts\.(?:googleapis|gstatic)\.com/i.test(read(f))));
htmls.forEach(f=>{
 const s=read(f); check(`zoom allowed ${f}`,/name=["']viewport["']/i.test(s)&&/user-scalable=yes/i.test(s)&&/maximum-scale=5/i.test(s));
 if(f!=='index.html') check(`font css linked ${f}`,s.includes('css/vazir-system.css?v=font1'));
});
const index=read('index.html'), promo=read('js/promo-slider.js'), promoCss=read('css/promo-slider.css'), adminHtml=read('admin.html'), admin=read('js/admin.js'), pro=read('js/admin-professional-v4.js'), proCss=read('css/admin-professional-v4.css'), server=read('server/server.js');
check('root retains one smart critical stylesheet',(index.match(/<link[^>]+rel=["']stylesheet["']/g)||[]).length===1&&index.includes('westo-critical.smart.css?v=release13r7'));
check('smart loader current release key',index.includes('westo-smart-loader.js?v=release13r7'));
check('promo explicitly mounts before catbar',promo.includes('catbar.parentNode.insertBefore(aside, catbar)'));
check('promo measures real navbar geometry',promo.includes('getBoundingClientRect()')&&promo.includes('--menu-nav-live-h'));
check('promo resize observes navbar and rail',promo.includes('ResizeObserver')&&promo.includes('resizeObserver?.observe(nav)')&&promo.includes('resizeObserver?.observe(aside)'));
check('promo zero-space without slides',promo.includes("root.classList.remove('has-westo-promo')")&&promo.includes("removeProperty('--menu-promo-h')"));
check('promo css consumes live nav height',promoCss.includes('--menu-nav-live-h'));
check('promo admin explains placement',admin.includes('صفحه ورود با Card Deck آزاد')&&admin.includes('داخل منو با Promo Rail'));
check('promo admin explicit publish control',admin.includes('data-promo-visibility'));
check('professional admin css loaded',adminHtml.includes('admin-professional-v4.css?v=adminPro4'));
check('professional admin js loaded',adminHtml.includes('admin-professional-v4.js?v=adminPro4'));
check('admin navigation finder exists',pro.includes('admin-nav-search'));
check('admin contextual guide exists',pro.includes('admin-workspace-guide'));
check('admin keyboard aids exist',pro.includes("event.key === '/'")&&pro.includes("event.altKey"));
check('admin mobile tables use data labels',pro.includes('dataset.label')&&proCss.includes('content:attr(data-label)'));
check('admin filters persist per workspace',pro.includes('sessionStorage')&&pro.includes('westo:admin:filter'));
check('admin save feedback has timestamp',admin.includes('ذخیره شد ·'));
check('admin surfaces request IDs on workspace failures',admin.includes('X-Request-Id')&&admin.includes('admin-request-id'));
check('production debug route gated',server.includes("if (process.env.NODE_ENV !== 'production')")&&server.includes("app.post('/api/debug-log'"));
check('cross-domain plugin header disabled',server.includes('X-Permitted-Cross-Domain-Policies'));
check('OTP requested legacy behavior retained',server.includes('matches the pre-admin-hardening WESTO OTP behaviour'));
check('service worker registration remains absent',!index.includes('pwa-register.js')&&!index.includes('navigator.serviceWorker.register'));
const baseline=JSON.parse(read('docs/admin-1000/BASELINE-CONTRACT.json'));
const tabs=[...adminHtml.matchAll(/data-tab=["']([^"']+)["']/g)].map(m=>m[1]).sort();
const routes=[]; for(const m of server.matchAll(/app\.(get|post|put|patch|delete)\(\s*["'`]([^"'`]+)["'`]/g)) routes.push(`${m[1].toUpperCase()} ${m[2]}`); routes.sort();
check('all 28 admin tabs preserved',tabs.length===28&&baseline.tabs.every(t=>tabs.includes(t))&&tabs.every(t=>baseline.tabs.includes(t)));
check('all baseline routes preserved',baseline.routes.every(r=>routes.includes(r)));
check('route count remains baseline-compatible',routes.length===baseline.routes.length);
console.log(JSON.stringify({pass,fail,failures,htmlCount:htmls.length,tabCount:tabs.length,routeCount:routes.length},null,2)); if(fail)process.exit(1);
