'use strict';
const fs=require('fs'); const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const index=read('index.html'), css=read('css/westo-production-v12.css'), js=read('js/westo-production-v12.js'), build=read('scripts/build-smart-bundles.js'), three=read('js/three-scene.js'), loader=read('js/westo-smart-loader.js'), server=read('server/server.js');
const release=(loader.match(/const VERSION = '([^']+)'/)||[])[1]||'';
let pass=0,fail=0,failures=[]; function check(name,ok){ if(ok)pass++;else{fail++;failures.push(name)} }
check('v12 critical css bundled',build.includes("'css/westo-production-v12.css'"));
check('v12 presentation js bundled',build.includes("'js/westo-production-v12.js'"));
check('v11 css removed from root critical bundle',!build.includes("'css/westo-production-v11.css'"));
check('v11 js removed from root app bundle',!build.includes("'js/westo-production-v11.js'"));
check('active release index cache key',release&&index.includes(`westo-critical.smart.css?v=${release}`)&&index.includes(`westo-smart-loader.js?v=${release}`));
check('active release loader key',Boolean(release));
check('active release early hints',release&&server.includes(`westo-app.smart.js?v=${release}`));
check('active release postprocessing key',release&&three.includes(`westo-postprocessing.bundle.mjs?v=${release}`));
check('entrance zero flex crush guard',css.includes('.eg-experience {')&&/flex\s*:\s*none/.test(css));
check('entrance grid bands',css.includes('grid-template-rows: minmax(0,auto) auto auto minmax(0,1fr) auto'));
check('entrance short desktop mode',css.includes('@media (min-width: 768px) and (max-height: 850px)'));
check('entrance mobile independent composition',css.includes('@media (max-width: 767px)'));
check('approved micro pattern token',css.includes("westo-micro-pattern-v8.png"));
check('approved CTA crop token',css.includes("westo-cta-pattern-v8.webp"));
check('theme wordmark swap',css.includes("westo-fa-wordmark-dark.png"));
check('hero legacy title hidden',css.includes('.carousel_title-collection')&&css.includes('visibility:hidden'));
check('hero v12 copy mounted',js.includes('westo-v12-hero-copy'));
check('hero category strip owned by v12',js.includes("heroCats = document.createElement('nav')"));
check('hero category clicks delegate carousel',js.includes('window.carousel?.goTo'));
check('hero lower editorial band',css.includes('--v12-hero-dock-h'));
check('hero short-height compact mode',css.includes('@media(max-height:850px) and (min-width:768px)'));
check('dish category bar centered',css.includes('left:50% !important')&&css.includes('translateX(-50%)'));
check('dish media fixed',css.includes('dish-board-media{position:fixed!important'));
check('dish card fixed',css.includes('#westo-dish-card.is-shared-dish-card{\n  position:fixed!important'));
check('dish rail fixed',css.includes('benefits_nav.is-menu-rail{\n  position:fixed!important'));
check('mobile dish card own bottom band',css.includes('--dish-card-stack'));
check('desktop dish three-zone variables',css.includes('--menu-card-w')&&css.includes('--menu-rail-w'));
check('mobile dish 390 guard',css.includes('@media(max-width:430px)'));
check('classic menu 390 overflow guard',css.includes('classic-menu .cm-header__bar'));
check('guest pages receive v12 cascade',['about.html','feedback.html','login.html','menu.html','order.html','profile.html','reserve.html'].every(p=>read(p).includes('westo-production-v12.css?v=prod13')));
check('mobile hero plate fit reduced',three.includes('promoHeightBudget')&&three.includes(': 0.50'));
check('desktop hero plate active scale refined',three.includes('const widthBudget = lerp(0.19, 0.36, centerWeight);')&&three.includes('scale: lerp(1.10, 0.98, compact)'));
check('economy blur fallback',css.includes("data-perf-tier='economy'"));
check('reduced motion fallback',css.includes('prefers-reduced-motion:reduce'));
check('QA geometry auditor exported',js.includes('window.westoV12QA = { audit'));
check('admin pattern remains replaceable',js.includes('syncAdminPattern')&&js.includes('deriveMicroPattern'));
console.log(JSON.stringify({pass,fail,failures},null,2)); if(fail)process.exit(1);
