const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname,'..');
const read = (p)=>fs.readFileSync(path.join(root,p),'utf8');
const css=read('css/westo-production-v12.css');
const prod=read('js/westo-production-v12.js');
const cart=read('js/table-cart.js');
const classic=read('js/classic-menu.js');
const menu=read('menu.html');
const order=read('order.html');
const checkout=read('js/checkout.js');
const checkoutCss=read('css/checkout.css');
const i18n=read('js/i18n.js');
const login=read('login.html');
const profile=read('profile.html');
const reserve=read('reserve.html');
const feedback=read('feedback.html');
const about=read('about.html');
const panelCss=read('css/panel.css');
const index=read('index.html');
const loader=read('js/westo-smart-loader.js');
const server=read('server/server.js');
const three=read('js/three-scene.js');
const checks=[];
const check=(name,pass)=>checks.push({name,pass:!!pass});
check('QA8 escaped CSS newline corruption removed', !css.includes('\\n'));
check('hero mask extra closing brace removed', !css.includes('transparent 97%);\n}}\n\n/* Dish mode'));
check('light secondary text token upgraded', css.includes('--prod-muted:rgba(34,40,38,.66);'));
check('hero progress rail is aria-hidden', prod.includes('class="westo-v12-hero-rail" aria-hidden="true"'));
check('hero rail no longer binds duplicate click navigation', !prod.includes("heroRail.addEventListener('click', onRailClick)"));
check('hero rail renders passive span markers', prod.includes('`<span class="westo-v12-hero-dot"'));
check('hero category toolbar semantic exists', prod.includes("heroCats.setAttribute('role', 'toolbar')"));
check('hero categories support roving keyboard navigation', prod.includes('function onHeroCategoryKeydown') && prod.includes("['ArrowLeft','ArrowRight','Home','End']"));
check('hero category state exposes aria-current', prod.includes("b.setAttribute('aria-current', on ? 'true' : 'false')"));
check('hero category state owns one tabindex', prod.includes('b.tabIndex = on ? 0 : -1'));
check('hero category nav label is language-aware', prod.includes("lang() === 'en' ? 'Categories'"));
check('dish mode removes hero direct navigation surface', css.includes('html.is-dish-boards .westo-prod-hero-cats { display:none!important; }'));
check('smallest hero removes competing carousel arrows', css.includes("html:not(.is-dish-boards) .carousel_arrow{display:none!important}"));
check('mobile category labels retained at readable compact size', css.includes('.westo-dish-catbar__label{font-size:9px!important'));
check('small mobile dish rail labels are not image-only', css.includes('.benefits_nav.is-menu-rail .benefits_rail-label{\n    display:-webkit-box!important'));
check('active states do not depend on color alone', css.includes('.westo-prod-hero-cat.is-active::after'));
check('keyboard focus is explicit for hierarchy navigators', css.includes('.westo-prod-hero-cat:focus-visible'));
check('reduced motion removes transform decoration', css.includes('@media(prefers-reduced-motion:reduce)') && css.includes('transform:none!important'));
check('quantity visualViewport CSS is real CSS', css.includes('.qty-modal.is-keyboard-open{height:var(--vv-height,100dvh)'));
check('modal close/quantity targets are at least 44px', css.includes('.qty-modal__x,.table-drawer__close,.qty-circle') && css.includes('min-width:44px!important;min-height:44px!important'));
check('cart drawer open is idempotent', cart.includes('const wasHidden = drawer.hidden;') && cart.includes('if (wasHidden) lockScroll();'));
check('quantity open is idempotent', cart.includes('const wasHidden = qtyModal.hidden;') && cart.includes('if (wasHidden) lockScroll();'));
check('cart focus trap retained', cart.includes('trapFocus(e, qtyModal.querySelector') && cart.includes('trapFocus(e, drawer.querySelector'));
check('cart visualViewport retained', cart.includes('function syncDrawerViewport') && cart.includes('function syncQtyViewport'));
check('classic scroll lock is idempotent', classic.includes('let classicScrollLocked = false;') && classic.includes('if (classicScrollLocked) return;'));
check('classic detail repaint preserves focus origin', classic.includes('const wasHidden = els.detail.hidden;') && classic.includes('if (wasHidden) overlayFocusBeforeOpen = document.activeElement'));
check('classic detail repaint does not refocus close repeatedly', classic.includes("if (wasHidden) requestAnimationFrame(() => els.detail.querySelector('.cm-detail__x')"));
check('classic drawer repeated open does not overwrite origin', classic.includes('const wasHidden = els.drawer.hidden;') && classic.includes('if (next && wasHidden) overlayFocusBeforeOpen'));
check('classic mixed-language subcopy remains auto-directional', classic.includes('class="cm-item__en" dir="auto"'));
check('release12 root cache generation', index.includes('westo-app.smart.js?v=release12') && index.includes('westo-critical.smart.css?v=release12'));
check('release12 smart loader generation', loader.includes("const VERSION = 'release12'"));
check('release12 server early hints', server.includes('westo-app.smart.js?v=release12'));
check('release12 three postfx generation', three.includes('westo-postprocessing.bundle.mjs?v=release12'));
check('classic menu source versions bumped', menu.includes('westo-production-v12.css?v=prod12.9') && menu.includes('table-cart.js?v=logic9') && menu.includes('classic-menu.js?v=logic9'));

check('checkout loads shared i18n before checkout logic', order.indexOf('js/i18n.js?v=logic9') < order.indexOf('js/checkout.js?v=logic9'));
check('checkout static workflow is i18n-keyed', order.includes('data-i18n="checkout.chooseFood"') && order.includes('data-i18n="checkout.fulfillmentTitle"') && order.includes('data-i18n="checkout.successKicker"'));
check('checkout dynamic menu names/descriptions are localized', checkout.includes('itemName(item)') && checkout.includes('itemDesc(item)') && checkout.includes('categoryTitle(category)'));
check('checkout currency and numerals follow active locale', checkout.includes("toLocaleString(localeTag())") && checkout.includes("tr('currency.toman')"));
check('checkout no Persian UI literals remain in dynamic JS', !/[\u0600-\u06FF]/.test(checkout));
check('checkout direct touch controls meet 44px target', checkoutCss.includes('.checkout-add { width: 44px; height: 44px') && checkoutCss.includes('.checkout-cart-line__actions button { width: 44px; height: 44px; }'));
check('checkout supported language direction is explicit', checkoutCss.includes("html[lang='fa'] .checkout-body") && checkoutCss.includes("html[lang='en'] .checkout-body"));
check('checkout economy header removes blur', checkoutCss.includes("html[data-perf-tier='economy'] .checkout-header"));
check('newsletter email label is programmatically associated', index.includes('label-input" for="EMAIL"'));
check('newsletter honeypot is outside keyboard and a11y flow', index.includes('name="email_address_check" aria-hidden="true" tabindex="-1"'));
check('legacy icon-only section links have accessible names', (index.match(/data-i18n-aria="legacy\.section[1-4]"/g)||[]).length === 4);
check('login OTP has five accessible digit labels', (login.match(/aria-label="رقم [1-5] کد تأیید"/g)||[]).length === 5);
check('login inherits shared language system', login.includes('js/i18n.js?v=logic9') && login.includes('data-i18n="auth.phoneIntro"'));
check('profile phone label is associated', profile.includes('<label for="phone" data-i18n="profile.phone">'));
check('profile uses locale-aware dates and points', profile.includes('toLocaleDateString(localeTag()') && profile.includes("toLocaleString(localeTag())"));
check('reservation inherits shared language system', reserve.includes('js/i18n.js?v=logic9') && reserve.includes('data-i18n="reserve.title"'));
check('reservation time choices expose named group semantics', reserve.includes('role="group" aria-labelledby="reserve-time-label"'));
check('feedback inherits shared language system', feedback.includes('js/i18n.js?v=logic9') && feedback.includes('data-i18n="feedback.nps"'));
check('feedback NPS choices expose named group semantics', feedback.includes('role="group" aria-labelledby="feedback-nps-label"'));
check('feedback NPS targets do not compress into eleven tiny columns', feedback.includes('grid-template-columns: repeat(6, minmax(44px, 1fr));'));
check('guest panel direction follows active language', panelCss.includes("html[lang='en'] body.panel-body { direction: ltr; }"));
check('guest flow focus-visible treatment is explicit', panelCss.includes('body.panel-body button:focus-visible'));
check('guest compact buttons maintain 44px minimum', panelCss.includes('body.panel-body .btn.btn-sm { min-height: 44px; }'));
check('guest economy tier removes secondary glass blur', panelCss.includes("html[data-perf-tier='economy'] body.panel-body .auth-card"));
check('about page i18n generation aligned', about.includes('js/i18n.js?v=logic9') && about.includes('data-i18n="nav.about"'));

check('guest panel CSS cache generation is bumped', [login,profile,reserve,feedback,order].every((x)=>x.includes('css/panel.css?v=logic9')));
check('checkout CSS cache generation is bumped', order.includes('css/checkout.css?v=logic9'));

check('all main guest documents expose translatable document titles', [index,menu,order,login,profile,reserve,feedback,about].every((x)=>x.includes('<title data-i18n=')));
check('1000-parameter matrix exists', fs.existsSync(path.join(root,'docs/design-logic-v12.9/DESIGN-LOGIC-1000.csv')));
const fail=checks.filter(x=>!x.pass);
console.log(JSON.stringify({pass:checks.length-fail.length,fail:fail.length,failures:fail.map(x=>x.name),checks},null,2));
process.exitCode=fail.length?1:0;
