'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const table = read('js/table-cart.js');
const loader = read('js/westo-smart-loader.js');
const three = read('js/three-scene.js');
const menuCss = read('css/menu-story.css');
const promoJs = read('js/promo-slider.js');
const promoCss = read('css/promo-slider.css');
const server = read('server/server.js');
const admin = read('js/admin.js');
const adminHtml = read('admin.html');
const build = read('scripts/build-smart-bundles.js');
const index = read('index.html');
let pass=0, fail=0; const failures=[];
const check=(name,ok)=>{ if(ok) pass++; else {fail++; failures.push(name);} };

check('staged progress lands at 100 only at end', table.includes('return (bucket + softstep(local)) / FLOCK_STAGES;') && !table.includes('/ (FLOCK_STAGES - 1)'));
check('handoff keeps flying while media is under orbs', table.includes("'is-dish-boards', 'is-cat-flying', 'is-cat-fly-media-under', 'is-cat-fly-handoff'"));
check('viewport observer yields during handoff', table.includes("root.classList.contains('is-cat-fly-handoff')"));
check('pending dish reveal accepts explicit element', table.includes('function revealPendingDishBoard(explicitEl = pendingDishRevealEl)'));
check('reverse handoff keeps transition ownership through double paint', table.includes('catFlyReverseGraceUntil') && table.includes('catFlyBusy = true;') && table.includes('doubleRaf(finish)'));
check('reverse handoff cannot re-enter dish mode in same scroll tick', table.includes('Date.now() < catFlyReverseGraceUntil') && table.includes("'is-dish-boards'"));
check('canonical Lenis scroll owner', table.includes('unbinding native') || (table.includes('unbindNative()') && table.includes('__westoDishViewportBound')));
check('catbar covers are eager session-pinned', table.includes("loading = 'eager'") && table.includes('pinned: true') && table.includes('nonPreemptible: true'));
check('catbar broken blob can be re-minted', table.includes('refreshReadyUrl') && loader.includes('function refreshReadyUrl'));
check('resource cleanup revokes all minted URLs only on true unload', loader.includes('task.objectUrls') && loader.includes('if (event.persisted)'));
check('idle background fill warms every category cover', loader.includes('startBackgroundFill') && loader.includes("warmCategoryCover(cat.cover, P.NEAR, 'fill:covers')"));
check('idle background fill warms menu images', loader.includes("warmOne(url, P.BACKGROUND, 'fill:menu')"));
check('responsive coordinator defers during cat fly', three.includes("classList.contains('is-cat-flying')") && three.includes('setTimeout(scheduleResponsiveResize, 120)'));
check('responsive dish path has one authoritative relayout', three.includes("inDishMode && typeof window.westoRelayout === 'function'") && three.includes('window.westoRelayout();'));
check('responsive settle is post-layout RAF', three.includes("requestAnimationFrame(() =>") && three.includes("new CustomEvent('westo:responsive-settle'"));
check('promo css affects catbar/dish chrome geometry', menuCss.includes('var(--menu-promo-h, 0px)') && menuCss.includes('var(--menu-promo-gap, 0px)'));
check('promo slider is no-op with zero published slides', promoJs.includes("if (!slides.length)") && promoJs.includes("root.classList.remove('has-westo-promo')"));
check('promo slider inserted immediately below navbar', promoJs.includes("nav.insertAdjacentElement('afterend', aside)"));
check('promo slider uses scheduler', promoJs.includes('scheduler?.bindImage') && promoJs.includes('scheduler?.requestImage'));
check('promo category/dish actions reuse menu state machine', promoJs.includes('westoOpenMenuTarget') && table.includes('window.westoOpenMenuTarget'));
check('promo module bundled in menu runtime', build.includes("'js/promo-slider.js'"));
check('promo CSS bundled in critical cascade', build.includes("'css/promo-slider.css'"));
check('admin promo tab exists', adminHtml.includes('data-tab="promoSlides"') && admin.includes('async promoSlides()'));
check('admin promo capability is content.manage', admin.includes("promoSlides: 'content.manage'"));
check('server has promo CRUD and public metrics', server.includes("'/api/admin/promo-slides'") && server.includes("'/api/promo-slides/:id/impression'") && server.includes("'/api/promo-slides/:id/click'"));
check('no default promo card is hardcoded in HTML', !index.includes('WESTO SOCIAL') && !index.includes('westo-promo-slider'));
check('service worker stays disabled', !index.includes('pwa-register.js') && !index.includes('sw.js'));
check('critical parser refs use current release cache key', index.includes('westo-critical.smart.css?v=release13r6') && index.includes('westo-smart-loader.js?v=release13r6'));

console.log(JSON.stringify({pass, fail, failures}, null, 2));
if(fail) process.exit(1);
