'use strict';
const fs=require('fs');
const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const entrance=read('js/entrance-promo-deck.js');
const entranceCss=read('css/entrance-promo-deck.css');
const menuPromo=read('js/promo-slider.js');
const admin=read('js/admin.js');
const server=read('server/server.js');
const build=read('scripts/build-smart-bundles.js');
const app=read('js/westo-app.smart.js');
const critical=read('css/westo-critical.smart.css');
const db=JSON.parse(read('server/data/db.json'));
const checks=[];
const check=(name,ok)=>checks.push({name,pass:!!ok});
check('entrance source module exists',entrance.includes('Entrance Promo Deck v14.4'));
check('free 2D pointer tracking',entrance.includes('dx=e.clientX-sx')&&entrance.includes('dy=e.clientY-sy'));
check('distance and velocity throw threshold',entrance.includes('distance>threshold')&&entrance.includes('speed>8.5'));
check('outgoing card appends to deck tail',entrance.includes('deck.appendChild(current)'));
check('incoming card promotes during drag',entrance.includes('stackAt(1-.6*p)'));
check('third card advances shelf during drag',entrance.includes('stackAt(2-.6*p)'));
check('intro fan and recurring affordance exist',entrance.includes('function fanDeck')&&entrance.includes('function scheduleIdleNudge'));
check('throw returns card to circular deck with spring',entrance.includes("duration:reduced?1:460")&&entrance.includes('cubic-bezier(.34,1.4,.5,1)'));
check('CSS transition fallback covers limited webviews',entrance.includes("typeof node?.animate==='function'")&&entrance.includes('function animateCard'));
check('snap back exists',entrance.includes('function snapBack()'));
check('reduced motion path exists',entrance.includes('prefers-reduced-motion: reduce'));
check('share is isolated from drag',entrance.includes("closest('.eg-promo__share')")&&entrance.includes('stopPropagation'));
check('native share plus clipboard fallback',entrance.includes('navigator.share')&&entrance.includes('navigator.clipboard'));
check('action types preserve existing architecture',entrance.includes("type === 'category'")&&entrance.includes("type === 'dish'")&&entrance.includes("type === 'internal'"));
check('impression analytics wired',entrance.includes("report(slide.id,'impression')"));
check('click analytics wired',entrance.includes("report(slide.id,'click')"));
check('resource scheduler image binding used',entrance.includes('scheduler.bindImage')&&entrance.includes("group:'entrance-promo'"));
check('next image intent warmup used',entrance.includes('scheduler?.requestImage'));
check('entrance placement filter',entrance.includes("['entrance','both']"));
check('menu placement filter',menuPromo.includes("['menu','both']"));
check('server placement allowlist',server.includes("PROMO_PLACEMENTS = new Set(['entrance', 'menu', 'both'])"));
check('server publishes placement',server.includes('placement: PROMO_PLACEMENTS.has(slide.placement)'));
check('server publishes share flag',server.includes('shareEnabled: slide.shareEnabled !== false'));
check('new slides default to entrance',server.includes("placement: 'entrance', shareEnabled: true"));
check('admin placement control',admin.includes('ps_placement_')&&admin.includes('صفحه ورود — داخل بخش تجربه'));
check('admin share control',admin.includes('ps_share_')&&admin.includes('دکمه اشتراک‌گذاری'));
check('admin entrance image validation',admin.includes('اسلاید صفحه ورود باید تصویر داشته باشد'));
check('admin entrance preview link',admin.includes('پیش‌نمایش صفحه ورود'));
check('css six-row layout only when promo exists',entranceCss.includes('.has-eg-promo .eg-card')&&entranceCss.includes('grid-template-rows'));
check('css dark/light material coverage',entranceCss.includes("html[data-theme='light']")&&entranceCss.includes('.eg-promo__card'));
check('css mobile responsive coverage',entranceCss.includes('@media (max-width:767px)'));
check('css short landscape coverage',entranceCss.includes('(orientation:landscape)'));
check('css economy blur fallback',entranceCss.includes("data-perf-tier='economy'"));
check('touch deck owns direct manipulation',entranceCss.includes('touch-action:none'));
check('foundation bundle includes entrance deck',build.includes("'js/entrance-promo-deck.js'")&&app.includes('Entrance Promo Deck v14.4'));
check('critical bundle includes deck css',build.includes("'css/entrance-promo-deck.css'")&&critical.includes('WESTO Entrance Promotional Deck v14.4'));
const promos=db.promoSlides||[];
check('demo deck has three replaceable WESTO samples',promos.length>=3&&promos.slice(0,3).every(s=>s.placement==='entrance'&&s.image));
check('sample assets exist',promos.slice(0,3).every(s=>fs.existsSync(path.join(ROOT,s.image))));
check('sample autoplay defaults off',promos.slice(0,3).every(s=>Number(s.autoplayMs||0)===0));
const fail=checks.filter(c=>!c.pass);
for(const c of checks) console.log(`${c.pass?'PASS':'FAIL'}  ${c.name}`);
console.log(`
Entrance Promo v13.6: ${checks.length-fail.length}/${checks.length}`);
if(fail.length) process.exit(1);
