'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const css=read('css/westo-ultra-fine-v1.2.css');
const v143=read('css/westo-v14.3-ultra-fine.css');
const three=read('js/three-scene.js');
const entrance=read('js/westo-entrance.js');
const animations=read('js/animations.js');
const index=read('index.html');
const loader=read('js/westo-smart-loader.js');
const designLogic=read('js/design-logic-v13.js');
const server=read('server/server.js');
const build=read('scripts/build-smart-bundles.js');
const critical=read('css/westo-critical.smart.css');
const pwaCss=read('css/westo-pwa.css');
const landscapeCss=read('css/westo-landscape-recovery.css');
const dishCardCss=read('css/westo-dish-card-premium.css');
const promoDeck=read('js/entrance-promo-deck.js');
const promoDeckCss=read('css/entrance-promo-deck.css');
const entranceGeometry=read('css/westo-v14.3-ultra-fine.css');
const pwaBootstrap=read('js/pwa-bootstrap.js');
const manifest=read('manifest.webmanifest');
const sw=read('sw.js');
const release=(loader.match(/const VERSION = '([^']+)'/)||[])[1]||'';
let pass=0,fail=0;const failures=[];
const check=(n,ok)=>{if(ok)pass++;else{fail++;failures.push(n)}};

check('release includes WebP-only media delivery',release==='release14uf1d28-webp-only');
check('inline Persian-default migration guard exists',index.includes('data-westo-inline="persian-default"')&&index.includes("westo_menu_lang_explicit_v1")&&index.includes("localStorage.setItem('westo_menu_lang', 'fa')"));
check('index release coherence',index.includes(`westo-critical.smart.css?v=${release}`)&&index.includes(`westo-smart-loader.js?v=${release}`)&&index.includes(`westo-app.smart.js?v=${release}`));
check('server Early Hints coherence',server.includes(`westo-critical.smart.css?v=${release}`)&&server.includes(`westo-smart-loader.js?v=${release}`)&&server.includes(`westo-app.smart.js?v=${release}`));
check('Three postprocessing release coherence',three.includes(`westo-postprocessing.bundle.mjs?v=${release}`));
check('iOS standalone mode is detected',designLogic.includes('window.navigator.standalone === true')&&designLogic.includes("root.classList.toggle('is-standalone'"));
check('standalone mobile metadata exists',index.includes('apple-mobile-web-app-capable')&&index.includes('apple-mobile-web-app-status-bar-style'));
check('installable manifest exists',index.includes('manifest.webmanifest')&&manifest.includes('"display": "standalone"')&&manifest.includes('"start_url": "/?source=pwa"'));
check('PWA lifecycle bootstrap exists',pwaBootstrap.includes("navigator.serviceWorker.register('/sw.js'")&&pwaBootstrap.includes("root.classList.toggle('is-standalone'"));
check('standalone owns full 100vh',pwaCss.includes('html.is-standalone')&&pwaCss.includes('--westo-app-height: 100vh')&&pwaCss.includes('height: 100vh !important'));
check('safe area is included in category offset',pwaCss.includes('--westo-nav-total-h: calc(var(--v12-nav-h) + var(--westo-safe-top))')&&pwaCss.includes('top: calc(var(--westo-nav-total-h) + 4px)'));
check('standalone runtime avoids reduced visual viewport',designLogic.includes('standalone && !keyboard ? layoutH : visualH')&&three.includes('standaloneViewport'));
check('PWA APIs are never stale-cached',server.includes("app.get('/sw.js'")&&server.includes("app.get('/manifest.webmanifest'")&&server.includes("Service-Worker-Allowed"));
check('service worker is network-first and API-safe',sw.includes('networkFirstNavigation')&&sw.includes("url.pathname.startsWith('/api/')"));
check('standalone bottom clearance is shared',v143.includes('--westo-bottom-clearance')&&v143.includes('env(safe-area-inset-bottom, 0px)'));
check('mobile category arrows are restored',v143.includes('--westo-hero-arrow-size')&&v143.includes('place-items:center !important'));
check('symmetric edge scroll guides are restored',v143.includes('.hud_left-bottom .icon-scroll_wrapper')&&v143.includes('.hud_right-bottom .icon-scroll_wrapper'));
check('legacy centered mobile scroll clone is removed',animations.includes("document.querySelectorAll('.westo-scroll-hint--mobile').forEach"));
check('short viewport plate collision guard exists',three.includes('const mobileCompact = clamp((760 - mobileViewportHeight) / 240, 0, 1);')&&three.includes('canPosY += 0.42 * mobileCompact'));
check('short landscape uses split hero composition',three.includes('if (mobileLandscape) canPosX -= 3.0')&&v143.includes('(max-height:560px) and (orientation:landscape)'));
check('desktop dish card uses readable compact scale',dishCardCss.includes('--menu-card-w: clamp(380px, 31vw, 440px)')&&dishCardCss.includes('font-size: clamp(22px, 1.8vw, 27px)'));
check('desktop dish title avoids arbitrary word breaks',dishCardCss.includes('overflow-wrap: normal !important')&&dishCardCss.includes('word-break: normal !important'));
check('tablet dish card width is bounded and centered',dishCardCss.includes('width: min(calc(100vw - 28px), 720px)')&&dishCardCss.includes('transform: translateX(-50%)'));
check('phone dish card breakpoint remains independently owned',dishCardCss.includes('@media (max-width: 430px)'));
check('tablet and desktop Persian dish titles keep descenders visible',dishCardCss.includes('padding-block: 0.04em 0.14em')&&dishCardCss.includes('overflow: visible !important'));
check('landscape recovery is orientation-only',landscapeCss.includes('orientation: landscape')&&!landscapeCss.includes('@media screen and (max-width: 991px) {'));
check('landscape recovery separates all three scene families',landscapeCss.includes('html.is-dish-boards')&&landscapeCss.includes('westo-v12-hero-copy')&&landscapeCss.includes('#westo-entrance.has-eg-promo'));
check('landscape recovery ships in the critical bundle',build.includes("'css/westo-landscape-recovery.css'"));

check('desktop-only CSS guard exists',/@media \(min-width: 992px\)/.test(css));
check('mobile hero geometry not overridden by v1.2',!/@media \(max-width: 991px\)/.test(css)&&!/@media \(max-width: 767px\)/.test(css));
check('hero copy gets protected desktop band',css.includes('width: min(560px, 46vw) !important')&&css.includes('z-index: 24 !important'));
check('short desktop guard exists',css.includes('@media (min-width: 992px) and (max-height: 920px)'));
check('horizontal arrows moved beside central plate',css.includes('inset-inline-start: clamp(52px, 22vw, 340px)')&&css.includes('inset-inline-end: clamp(52px, 22vw, 340px)'));
check('canvas lower edge safety fade is desktop-only',css.includes('main.main-wrapper > canvas')&&css.includes('transparent 79%'));

check('desktop stage uses compact viewport factor',three.includes("const compact = clamp((960 - (window.innerHeight || 900)) / 260, 0, 1);"));
check('desktop stage center is raised',three.includes("{ s: 0, x: 0, y: lerp(0.48, 0.66, compact)"));
check('desktop stage center scale reduced',three.includes('scale: lerp(1.10, 0.98, compact)'));
check('desktop stage hides second-neighbor clutter',three.includes('if (s >= 1.72)'));
check('desktop stage keeps immediate neighbor',three.includes('{ s: 1, x: 3.78'));
check('desktop stage gets aspect-aware plate geometry',three.includes("const plateSize = can.userData?.plateSize;")&&three.includes('const widthBudget = lerp(0.19, 0.36, centerWeight);')&&three.includes('const heightBudget = lerp(0.26, 0.43, centerWeight);'));
check('desktop fit cap bounded',three.includes("centerWeight > 0.55 ? 1.12 : 0.70"));
check('carousel/state APIs untouched',three.includes('carousel.previous()')&&three.includes('carousel.next()')&&three.includes('carousel.goTo'));

check('entrance pattern resolves against document base URL',entrance.includes('new URL(src, document.baseURI).href'));
check('entrance pattern CSS variable remains same owner',entrance.includes("root.style.setProperty('--eg-pattern-image'"));
check('resource scheduler preserves WebP-only image delivery',loader.includes('Central resource scheduler / browser download manager.')&&loader.includes('async function requestImage')&&loader.includes('function webpImageUrl')&&!loader.includes('supportsAvif')&&loader.includes('requestImage,'));
check('category header lite preserved',read('js/table-cart.js').includes('westo-dish-catbar'));
check('promo deck behavior preserved',promoDeck.includes('throwCard')&&promoDeck.includes('snapBack'));
check('promo deck uses reference-like tactile stack',promoDeck.includes('const stackAt=')&&promoDeck.includes('{x:8,y:-16')&&promoDeck.includes('{x:6,y:-10')&&promoDeckCss.includes('cubic-bezier(.34,1.45,.5,1)'));
check('promo deck has intro fan and idle affordance',promoDeck.includes('function fanDeck')&&promoDeck.includes('function scheduleIdleNudge')&&promoDeck.includes('fanDeck({intro:true})'));
check('promo deck uses velocity-aware throw and spring return',promoDeck.includes('speed>8.5')&&promoDeck.includes("navigator.vibrate?.(14)")&&promoDeck.includes("duration:reduced?1:460"));
check('promo deck direct drag avoids transition lag',promoDeckCss.includes('.is-dragging .eg-promo__card { transition:none !important; }'));
check('promo deck has a Web Animations fallback',promoDeck.includes("typeof node?.animate==='function'")&&promoDeck.includes("node.style.transition=properties.join(',')"));
check('promo deck reserves stack rise and handles mobile-scale viewports',promoDeck.includes('syncDeckDensity')&&promoDeck.includes('shortDeck')&&entranceGeometry.includes('.eg-promo--compact')&&entranceGeometry.includes('.eg-experience--promo-safe')&&entranceGeometry.includes('(pointer:coarse) and (max-width:1024px)')&&entranceGeometry.includes('(max-aspect-ratio:4/5)'));
check('thermal governor preserved',read('js/westo-v14.3-ultra-fine.js').includes('dataset.thermalIdle'));
check('prior v1.1 scroll-copy correction preserved',v143.includes('canonical hero scroll instruction'));
check('PWA geometry is last smart CSS source',build.indexOf("'css/westo-pwa.css'")>build.indexOf("'css/westo-ultra-fine-v1.2.css'"));
check('critical bundle contains v1.2 guard',critical.includes('WESTO Ultra Fine v1.2 — desktop hero composition guard'));
check('critical bundle contains final PWA geometry',critical.includes('WESTO installed web app geometry'));

console.log(JSON.stringify({pass,fail,failures,release},null,2));
if(fail)process.exit(1);
