'use strict';
const fs=require('fs');const path=require('path');const ROOT=path.resolve(__dirname,'..');
const read=(r)=>fs.readFileSync(path.join(ROOT,r),'utf8');
const checks=[];const check=(name,ok,detail='')=>checks.push({name,ok:!!ok,detail});
const table=read('js/table-cart.js');
const css=read('css/westo-production-v12.css');
const app=read('js/westo-app.smart.js');
const menu=read('js/westo-menu.smart.js');
const build=read('scripts/build-smart-bundles.js');
const index=read('index.html');const loader=read('js/westo-smart-loader.js');const server=read('server/server.js');const three=read('js/three-scene.js');
const release=(loader.match(/const VERSION = '([^']+)'/)||[])[1]||'';
check('active release index cache',release&&index.includes(`westo-critical.smart.css?v=${release}`)&&index.includes(`westo-smart-loader.js?v=${release}`));
check('active release loader',Boolean(release));
check('active release early hints',release&&server.includes(`westo-app.smart.js?v=${release}`));
check('active release postFX',release&&three.includes(`westo-postprocessing.bundle.mjs?v=${release}`));
check('single canonical catbar signature',table.includes('|lite1|'));
check('single canonical copy',table.includes("track.dataset.loopCopies = '1'")&&table.includes('order.forEach((id, index) => appendChip(id, index, 1))'));
check('infinite class removed on rebuild',table.includes("track.classList.remove('is-infinite')"));
check('native scroll binding only',/function bindCatBarInfiniteScroll\(track\)[\s\S]{0,520}bindCatBarUserScroll\(track\);[\s\S]{0,120}bindCatBarPageWheel\(\);[\s\S]{0,120}return track;/.test(table));
check('no catbar indicator geometry scheduler',table.includes('function scheduleDishCatBarIndicator() {}')&&table.includes('function updateDishCatBarIndicator() {}'));
check('legacy neon observer removed from app bundle',!app.includes('category-neon-indicator.js'));
check('legacy neon observer removed from menu bundle',!menu.includes('category-neon-indicator.js'));
check('legacy neon observer removed from build graph',!build.includes('category-neon-indicator.js'));
check('coarse pointer skips page-wide touch stepping',table.includes("window.matchMedia('(pointer: coarse)').matches) return"));
check('touch hover prefetch suppressed',table.includes("if (e.pointerType === 'touch') return;"));
check('native center path',table.includes("behavior: instant ? 'auto' : 'smooth'"));
check('diagnostics API',table.includes('window.westoCatbarDiagnostics'));
check('catbar backdrop disabled',/#westo-dish-catbar\.westo-dish-catbar[\s\S]{0,800}backdrop-filter:\s*none !important/.test(css));
check('full-bar geometry marker removed',/#westo-dish-catbar::before[\s\S]{0,160}content:\s*none !important/.test(css));
check('chip keyframes disabled',/#westo-dish-catbar \.westo-dish-catbar__chip[\s\S]{0,220}animation:\s*none !important/.test(css));
check('thumb filters disabled',/#westo-dish-catbar \.westo-dish-catbar__thumb[\s\S]{0,180}filter:\s*none !important/.test(css));
check('active underline local + static',/#westo-dish-catbar \.westo-dish-catbar__chip\.is-active::after[\s\S]{0,600}animation:\s*none !important/.test(css));
check('mobile transitions disabled',/@media \(max-width: 991px\), \(pointer: coarse\)[\s\S]{0,1100}transition:\s*none !important/.test(css));
const ids=[7560,7561,7562,7563,7564,7566,7567,7599,7675,7676,7697,7701,9478,13581,14477,17007];
let bytes=0;let all=true;let max=0;
for(const id of ids){const p=path.join(ROOT,`assets/menu/category-thumbs/category-${id}.webp`);if(!fs.existsSync(p)){all=false;continue;}const b=fs.statSync(p).size;bytes+=b;max=Math.max(max,b);}
check('all 16 dedicated thumbnails exist',all,`${ids.length} expected`);
check('thumbnail pack <= 100 KB',bytes<=100*1024,`${bytes} bytes`);
check('each thumbnail <= 10 KB',max<=10*1024,`${max} max bytes`);
const failed=checks.filter(x=>!x.ok);console.log(JSON.stringify({summary:{passed:checks.length-failed.length,failed:failed.length,total:checks.length},checks},null,2));
process.exitCode=failed.length?1:0;
